# Generated by Django 4.0.1 on 2022-01-15 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=40)),
                ('sensor_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Sensors.sensortype')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=40)),
                ('reading_datetime', models.DateTimeField()),
                ('reading_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Sensors.readingtype')),
                ('sensor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Sensors.sensortype')),
            ],
        ),
    ]
