# Generated by Django 4.0.1 on 2022-01-15 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Sensors.sensor'),
        ),
    ]
