# Generated by Django 4.0.1 on 2022-01-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0003_device_devicestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
