# Generated by Django 4.0.1 on 2022-01-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0004_datedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='reading_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Sensors.readingtype'),
        ),
    ]
