# Generated by Django 4.0.1 on 2022-01-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0005_alter_reading_reading_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='reading_type',
        ),
        migrations.DeleteModel(
            name='ReadingType',
        ),
    ]
