# Generated by Django 4.0.2 on 2022-03-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0006_remove_reading_reading_type_delete_readingtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='datedimage',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sensors.camera'),
        ),
    ]
