# Generated by Django 4.0.2 on 2022-03-18 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0007_camera_datedimage_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='datedimage',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbs/'),
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, max_length=40, null=True)),
                ('width', models.FloatField(blank=True, max_length=40, null=True)),
                ('length', models.FloatField(blank=True, max_length=40, null=True)),
                ('sensor_dist', models.FloatField(blank=True, max_length=40, null=True)),
                ('default_ppm', models.IntegerField(default=150)),
                ('default_ph', models.FloatField(default=7, max_length=40)),
                ('target_ppm', models.IntegerField(default=500)),
                ('target_ph', models.FloatField(default=6.5, max_length=40)),
                ('n', models.IntegerField(default=0)),
                ('p', models.IntegerField(default=0)),
                ('k', models.IntegerField(default=0)),
                ('level_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='level', to='Sensors.sensor')),
                ('ph_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ph', to='Sensors.sensor')),
                ('ppm_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ppm', to='Sensors.sensor')),
            ],
        ),
    ]
