# Generated by Django 4.0.2 on 2022-03-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0008_datedimage_thumb_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='tank_name',
            field=models.CharField(default='Water Tank', max_length=40),
        ),
    ]
