# Generated by Django 4.0.2 on 2022-03-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0009_tank_tank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datedimage',
            name='category',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='datedimage',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='datedimage',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
