# Generated by Django 4.0.1 on 2022-01-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sensors', '0004_datedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=40)),
                ('type_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('info_url', models.URLField()),
                ('determinate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('date_sprouted', models.DateField(blank=True, null=True)),
                ('date_died', models.DateField(blank=True, null=True)),
                ('plant_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Plants.plantstatus')),
                ('plant_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Plants.planttype')),
                ('soil_sensor', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Sensors.sensor')),
            ],
        ),
    ]
