# Generated by Django 4.0.2 on 2022-03-18 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0008_datedimage_thumb_tank'),
        ('Plants', '0002_plant_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='planter_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='preferred_ph',
            field=models.FloatField(default=6.5, max_length=40),
        ),
        migrations.AddField(
            model_name='plant',
            name='preferred_ppm',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='plant',
            name='tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Sensors.tank'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil_sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Sensors.sensor'),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plants.plantmedium'),
        ),
    ]
