# Generated by Django 4.0.2 on 2022-03-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0003_plantmedium_plant_planter_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='preferred_ph',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='preferred_ppm',
        ),
        migrations.AddField(
            model_name='planttype',
            name='preferred_ph',
            field=models.FloatField(default=6.5, max_length=40),
        ),
        migrations.AddField(
            model_name='planttype',
            name='preferred_ppm',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='info_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
