# Generated by Django 4.0.2 on 2022-03-31 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0004_remove_plant_preferred_ph_remove_plant_preferred_ppm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='clone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='parent1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children1', to='Plants.plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='parent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children2', to='Plants.plant'),
        ),
    ]
